FROM node:lts-alpine
RUN mkdir -p /usr/app
WORKDIR /usr/app

# Install Dependencies
COPY ./package*.json ./
COPY ./package-lock.json ./
RUN npm i -g @nestjs/cli
RUN npm install

# Copy app source code
COPY . .

# Ports
EXPOSE 4000

CMD [ "npm", "run", "start:dev"]
