
name: Node.js CI/CD

on:
  push:
    branches: 
    - main
    

jobs:
  build:
    runs-on: [self-hosted, Prod]
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
       touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
    - run: npm i  
    - run: npx prisma migrate deploy    
    - run: npx prisma generate
    - run: npm run build --if-present
    #- run: pm2 start dist/main.js --name=prodapi
    - run: pm2 restart prodapi
    - run: pm2 status
    
    
   
    
    
    
    
   
